spotless {
    java {
        target fileTree('.') {
            include '**/*.java'
            exclude '**/build/**', '**/build-*/**'
        }
        toggleOffOn()

        importOrder()
        removeUnusedImports()

        googleJavaFormat()
        formatAnnotations()

        endWithNewline()
        trimTrailingWhitespace()
        licenseHeader('/* Copyright $YEAR UnitedCloud. All rights reserved. */')
    }

    groovyGradle {
        target fileTree('.') {
            include '**/*.gradle'
            exclude '**/build/**', '**/build-*/**'
        }
        greclipse()
        indentWithSpaces(4)
        trimTrailingWhitespace()
        endWithNewline()
    }

    format 'xml', {
        target fileTree('.') {
            include '**/*.xml'
            exclude '**/build/**', '**/build-*/**', '**/.idea/**'
        }
        eclipseWtp('xml')
        trimTrailingWhitespace()
        indentWithSpaces(2)
        endWithNewline()
    }

    format 'misc', {
        target fileTree('.') {
            include '**/*.md', '**/.gitignore'
            exclude '**/build/**', '**/build-*/**'
        }
        trimTrailingWhitespace()
        indentWithSpaces(2)
        endWithNewline()
    }
}

tasks.register('codestyleCheck') {
    dependsOn 'spotlessCheck'
}

tasks.register('codestyle') {
    dependsOn 'spotlessApply'
}
